ARG BALENA_ARCH=%%BALENA_ARCH%%

FROM balenalib/$BALENA_ARCH-alpine

RUN install_packages dbus bash iproute2 iputils coreutils jq usbutils eudev-hwids

WORKDIR /app

COPY entry.sh gpio VERSION cellular_guard.env ./
RUN chmod 755 entry.sh gpio VERSION cellular_guard.env

ENTRYPOINT ["bash","./entry.sh"]
