version: 2.0
services:
  cellular_guard:
    build: .
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    labels:
      io.balena.features.dbus: '1' # dbus unix socket mount
      io.balena.features.sysfs: '1' # /sys mount
      io.balena.features.procfs: '1' # /proc mount
    network_mode: "host" # to access interface wwan0
    privileged: true # might need write /dev/ttyUSB2
    oom_kill_disable: true # disable be killed by OOM