ARG BALENA_ARCH=%%BALENA_ARCH%%

FROM balenalib/$BALENA_ARCH-alpine

RUN install_packages dbus bash iproute2 iputils coreutils jq usbutils

WORKDIR /app

COPY --chmod=755 entry.sh gpio VERSION cellular_guard.env ./

ENTRYPOINT ["bash","./entry.sh"]
